In [1]:
print("Hello World")

Hello World


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.6.0+cu124


##Intro to tensor


##Creating Tensor

In [6]:
##Intro to tensor

scalar = torch.tensor(7)
scalar
##Creating Tensor

tensor(7)

In [7]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [11]:
vector = torch.tensor([7,7])

In [16]:
vector.shape

torch.Size([2])

In [13]:
vector.ndim

1

In [21]:
matrix = torch.tensor([[7,7],[8,8]])

In [22]:
matrix.ndim

2

In [23]:
matrix.shape

torch.Size([2, 2])

In [24]:
matrix[1]

tensor([8, 8])

In [25]:
# Tensor
tensor = torch.tensor([[[1,2,3],[4,5,6]]])

In [26]:
tensor.ndim

3

In [27]:
tensor.shape

torch.Size([1, 2, 3])

In [28]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

##Random tensors
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random number  to better represntation

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`




In [43]:
#create a random tensor
random = torch.rand(10,10,10)


In [44]:
print(random)

tensor([[[4.9705e-02, 3.1026e-01, 9.5649e-01, 1.0853e-01, 5.3807e-01,
          9.9256e-01, 3.2220e-01, 3.9933e-01, 4.3012e-01, 5.8717e-01],
         [8.8506e-02, 6.0026e-01, 2.3272e-01, 7.6069e-01, 1.8405e-01,
          8.4727e-01, 3.1779e-02, 9.0218e-01, 4.4974e-01, 4.8118e-01],
         [5.3972e-01, 3.4970e-01, 6.6828e-01, 5.6426e-01, 7.3617e-02,
          2.4401e-01, 3.1578e-01, 1.3919e-01, 7.9763e-01, 3.0582e-01],
         [1.2742e-01, 5.1822e-02, 9.6650e-01, 2.0346e-02, 7.0309e-01,
          1.8056e-01, 4.0049e-01, 4.6521e-01, 7.4106e-01, 6.7286e-01],
         [3.7862e-01, 2.9192e-01, 6.4710e-01, 1.9652e-01, 9.0262e-01,
          6.0132e-01, 9.7905e-01, 7.9971e-01, 2.9561e-01, 7.7786e-02],
         [1.4356e-01, 2.6776e-01, 2.6012e-01, 6.8297e-01, 5.3558e-01,
          5.7632e-01, 4.5247e-01, 8.6736e-01, 5.5706e-01, 5.2735e-01],
         [5.2786e-01, 4.0147e-01, 7.1502e-01, 5.7493e-01, 1.5605e-01,
          7.7777e-01, 3.8523e-01, 7.7425e-01, 5.5455e-01, 1.9620e-01],
         [1.1

In [46]:
random.ndim

3

In [47]:
#create a tensor similar to image
random_image_size = torch.rand(size = (224,224,3))#height,width , color- R,G,B

In [48]:
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [51]:
###Challendge to create  a random tensor of whatever size i want
random2 = torch.rand(3,4,5)
print(random2)

tensor([[[0.6687, 0.4361, 0.4205, 0.2925, 0.4159],
         [0.8010, 0.1756, 0.3458, 0.4894, 0.7189],
         [0.2979, 0.3078, 0.1866, 0.1885, 0.5297],
         [0.4865, 0.7046, 0.6529, 0.2030, 0.4695]],

        [[0.5730, 0.8310, 0.9525, 0.3669, 0.6619],
         [0.5970, 0.4018, 0.3150, 0.4710, 0.5546],
         [0.1982, 0.3231, 0.0782, 0.7744, 0.9815],
         [0.9513, 0.4712, 0.2986, 0.0681, 0.8506]],

        [[0.1827, 0.3071, 0.4585, 0.1478, 0.3193],
         [0.8654, 0.0283, 0.4226, 0.5043, 0.0382],
         [0.7920, 0.2961, 0.6270, 0.5146, 0.4149],
         [0.3429, 0.2001, 0.4620, 0.0121, 0.3064]]])


In [53]:
##Tenor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
##Tenor with all zeros
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
##Creating a range of tensors
one_to_ten = torch.range(0,10)


<ipython-input-60-0b3448c42b8c>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(0,10)


In [59]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
one_to_ten

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
one_to_thous = torch.arange(0,end=1000, step = 77)
one_to_thous

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

###Tensor Datatype

In [70]:
###Tensor Datatype
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape
float_32_tensor.dtype
float_32_tensor.device

device(type='cpu')

In [71]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [72]:
##Getting info for tensor
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2690, 0.9736, 0.2029, 0.3512],
        [0.9403, 0.0751, 0.6709, 0.1265],
        [0.3862, 0.7378, 0.5485, 0.0887]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [73]:
###Manipulating Tensors(tensor operations)

In [77]:
tensor = torch.tensor([1,2,3])
tensor


tensor([10, 20, 30])

In [78]:
tensor + 12


tensor([13, 14, 15])

In [79]:
tensor*10

tensor([10, 20, 30])

In [80]:
tensor-10

tensor([-9, -8, -7])

In [82]:
#Try out in built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [83]:
torch.add(tensor,10)

tensor([11, 12, 13])

###Matrix multiplication
Two main ways of multiplication
1.Element wise
2.Matrix Multiplication(dot product -> symbol .)


In [85]:
##Element wise multiplication
print(tensor,'*',tensor)
print(f"Equals :{tensor*tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :tensor([1, 4, 9])


In [86]:
##Matrixmultiplication-> Matmul
print(torch.matmul(tensor,tensor))

tensor(14)


In [88]:
##by hand
value =0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)


In [91]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4400, 1.5678, 0.8176],
        [0.3360, 1.2971, 0.5741],
        [0.2173, 0.7098, 0.4361]])

In [97]:
tensor1 = torch.rand(3,2)

transpose = tensor1.T
tensor1

tensor([[0.6139, 0.8211],
        [0.2100, 0.9037],
        [0.7634, 0.8895]])

In [98]:
transpose

tensor([[0.6139, 0.2100, 0.7634],
        [0.8211, 0.9037, 0.8895]])

##Indexing with PyTorch is similar to indexing in NumPy


In [106]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [107]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [108]:
x[0][0]


tensor([1, 2, 3])

In [109]:
print(x[::2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


###Numpy -> scientific python numerical lib in pytorch
and becasue of this pytorch have the functionality to interact
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

###The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [111]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #by default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).



In [112]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [116]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2358, 0.8161, 0.0662, 0.1938],
        [0.1587, 0.3040, 0.4956, 0.1321],
        [0.7199, 0.1944, 0.6644, 0.3972]])

Tensor B:
tensor([[0.6605, 0.3604, 0.2165, 0.7110],
        [0.9666, 0.5255, 0.9754, 0.3808],
        [0.3937, 0.9992, 0.0227, 0.7814]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [117]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [118]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [120]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [121]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])